### ISSUE TITLE
stdlib::List<> insert compiles incorrectly

### ISSUE THREAD

**Issue by dshadowwolf** [ZenCodeLang/ZenCode#12]
Found when helping `juicebin` on Discord, an attempt to insert - `ingredients.insert(ingredients.indexOf(<item:immersiveengineering:fluid_pipe>), <item:create:fluid_pipe>);` was crashing with "Type 'com/blamejared/crafttweaker/api/item/IIngredient' (current frame, stack[3]) is not assignable to integer"

A run with `#debug` and a decompile found the line was coming out as: `ingredients.add((Object)index, (int)BracketHandlers.getItem("create:fluid_pipe"));` instead of the expected result.

[stdlib::List<>.insert()](https://github.com/ZenCodeLang/StdLibs/blob/adf1273fe89f117d446e40307ab4f50c5f64f532/src/main/zencode/stdlib/src/List.zs#L9-L10) - `insert` is mapped to `add` in [JavaPrepareDefinitionVisitor](https://github.com/ZenCodeLang/ZenCode/blob/84e75fa7b7c92b1873ce98fff3af9897b149835a/JavaShared/src/main/java/org/openzen/zenscript/javashared/prepare/JavaPrepareDefinitionVisitor.java#L66) so it resolving to `add` is understood, but the swapping of the parameters is not...

And... trying to disentangle things in the compiler is making me go crosseyed - I'm going to have to step away...

A bit more thought: [line 66](https://github.com/ZenCodeLang/ZenCode/blob/84e75fa7b7c92b1873ce98fff3af9897b149835a/JavaShared/src/main/java/org/openzen/zenscript/javashared/prepare/JavaPrepareDefinitionVisitor.java#L66) of JavaPrepareDefinitionVisitor looks to have the method signature wrong - it has `(Ljava/lang/Object;I)V` instead of `(I;Ljava/lang/Object)V` (I think... JVM internals is not my best field of knowledge)

**Comment by kindlich** [comment]
IIrc, this was already fixed, wasn't it?

**Comment by dshadowwolf** [comment]
Yes, shouldn't this have been auto-closed by the PR being accepted ?

**Comment by jaredlll08** [comment]
I believe it only closes if it has "close #X" or maybe "fix #X", not just any referenced issues.
