### ISSUE TITLE
can not handle double properly

### ISSUE THREAD

**Issue by friendlyhj** [ZenCodeLang/ZenCode#16]
https://gist.github.com/friendlyhj/ce35f1ae6eed311763a74b96c08450aa

but if i change these double to int, everything will be fine.

**Comment by kindlich** [comment]
Can you check if you have a similar issue when using long?
I assume that this issue rather has to do with long types as parameters rather than only doubles

**Comment by friendlyhj** [comment]
yea, I have the same issue.
