### ISSUE TITLE
JavaNativeTypeConverter#getFunctionalInterfaceMethod fails for UnaryOperator

### ISSUE THREAD

**Issue by jaredlll08** [ZenCodeLang/ZenCode#54]
Basically UnaryOperator has no methods itself, it just extends Function, since we use `getDeclaredMethods`, the method in Function even being looked at.

https://github.com/ZenCodeLang/ZenCode/blob/0a7dce467cac97c668c9df911801a12f2e727f63/JavaIntegration/src/main/java/org/openzen/zencode/java/module/converters/JavaNativeTypeConverter.java#L329

**Comment by friendlyhj** [comment]
```java
public class Main {

    public static void main(String[] args) {
        System.out.println(getFunctionalInterfaceMethod(UnaryOperator.class, true));
        System.out.println(getFunctionalInterfaceMethod(UnaryOperator.class, false));
    }

    public static Method getFunctionalInterfaceMethod(Class<?> functionalInterface, boolean declared) {
        Method[] methods = declared ? functionalInterface.getDeclaredMethods() : functionalInterface.getMethods();
        for (Method method : methods) {
            if (Modifier.isPublic(method.getModifiers()) && Modifier.isAbstract(method.getModifiers()) && !method.isDefault())
                return method;
        }

        return null;
    }
}
```
Result:
```text
null
public abstract java.lang.Object java.util.function.Function.apply(java.lang.Object)
```

So changing to `getMethods()` would fix the issue.

**Comment by jaredlll08** [comment]
Also confirmed that all the functions in https://github.com/ZenCodeLang/ZenCode/blob/85ee7496c233b740f2547b5b5672a74a25d7a33f/JavaShared/src/main/java/org/openzen/zenscript/javashared/JavaContext.java#L58-L113 pass with `declared = false`.
