### ISSUE TITLE
Array arguments don't cast nicely

### ISSUE THREAD

**Issue by jaredlll08** [ZenCodeLang/ZenCode#6]
```java
    public void addInscribeRecipe(String name, IItemStack output, IIngredient middleInput,
            @ZenCodeType.Optional IIngredient[] otherInputs);
```

For otherInputs
```zenscript
[<item:minecraft:dirt>]                  // doesn't work
[<item:minecraft:dirt>] as IIngredient[] // works
```

Ideally `IItemStack[]` should be auto cast to `IIngredient[]`

**Comment by jaredlll08** [comment]
Removing the Optional did make the issue go away, so it seems to be related to having an optioanl param (may only be arrays)

**Comment by stanhebben** [comment]
That will be the cause of it. The code that automatically determines the type of the array will not be unwrapping the optional, causing the type inference to fail. It should be a trivial fix, I'll look into it.
