### ISSUE TITLE
Java/StdLibs Math functions

### ISSUE THREAD

**Issue by kindlich** [ZenCodeLang/ZenCode#7]
As discussed in Discord, the Math functions (sin, cos, tan) and Fields (PI, E) should be in a separate Lib, rather than on a Host implementation.

That lib needs to provide definitions for these members (using NativeMember Annotations/externs if possible), and the implementation side (currently only Java) needs to provide Handles for the defined native members.

**Comment by jaredlll08** [comment]
merged in https://github.com/ZenCodeLang/ZenCode/pull/37
