### ISSUE TITLE
try-catch not allowing access to exception

### ISSUE THREAD

**Issue by dshadowwolf** [ZenCodeLang/ZenCode#89]
In testing the try-catch structure it appears that there is an issue when trying to reference the exception by the given name. 
```
[00:10:17.057][ERROR]: Execution for loader 'crafttweaker' completed with an error
java.lang.IllegalStateException: Local variable unknown
...
```

With the variable reference commented out, the code works fine and can even trap things like `Divide by Zero`. [The log](https://github.com/ZenCodeLang/ZenCode/files/8409904/crafttweaker.log) shows a fresh run showing the error and a reload with the line referencing the variable commented out. The full [test script](https://gist.github.com/dshadowwolf/7586e46fc25fec317c5549d0b03ec58e) is available and shows the various bits that are commented out to change things around.

When the code was run through a decompiler it seems to show that there is a variable available in the `catch` block, but with an automatically generated name (using Procyon it shows as `catch (Exception exception)` and `catch (ExceptionTest exceptionTest)` - under Fernflower the only thing that changes is the naming of the variable), so it does look like it is propagated into the scope, but something happens that means it is not known to ASM when it comes time to dereference it for access.

**Comment by kindlich** [comment]
Seems like an error in the StatementVisitor.
The catch-clause variable is not properly added as localVar in the javaWriter.
Simple solution would be to just treat it like a normal var expression instead of declaring it manually.

Inside JavaStatementVisitor#visitTryCatch we would need to adapt the catchClause for-loop to the code below.
Currently not at a computer where I can push and properly test this...

```java
		for (CatchClause catchClause : statement.catchClauses) {
			final Label catchStart = new Label();
			javaWriter.label(catchStart);

			catchClause.exceptionVariable.accept(this);
			final JavaLocalVariableInfo localVariable = javaWriter.getLocalVariable(catchClause.exceptionVariable.variable);
			javaWriter.store(localVariable.type, localVariable.local);

			catchClause.content.accept(this);
			final Label catchFinish = new Label();
			javaWriter.label(catchFinish);

			if (statement.finallyClause != null) {
				statement.finallyClause.accept(this);
				javaWriter.tryCatch(catchStart, catchFinish, finallyStart, null);
			}

			javaWriter.tryCatch(tryCatchStart, tryFinish, catchStart, localVariable.type.getInternalName());
			javaWriter.goTo(tryCatchFinish);
		}
```

**Comment by jaredlll08** [comment]
Can confirm that this works after swapping the exception order around
